baseURL: "https://abstractnonsense.xyz/"
languageCode: "en-au"
title: "Abstract Nonsense"

params:
  description: "A blog about Mathematics and Computer Science."
  math: true
  author:
    name: Yossi Frenkel
    email: hello@abstractnonsense.xyz

# Pagination settings
pagination: 
  pagerSize: 6

# Enable taxonomies for tags
taxonomies:
  tag: "tags"

enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
    extensions:
      # Reference: https://gohugo.io/content-management/mathematics
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true
      definitionList: true
      extras:
        mark:
          enable: true
  highlight:
    noClasses: false
    lineNos: false
    codeFences: true
    guessSyntax: true
