baseURL: "https://abstractnonsense.xyz/"
languageCode: "en-au"
title: "Abstract Nonsense"

params:
  description: "A blog about Mathematics and Computer Science."

# Pagination settings
pagination: 
  pagerSize: 6

# Enable taxonomies for tags
taxonomies:
  tag: "tags"

enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      definitionList: true
      extras:
        mark:
          enable: true
  highlight:
    noClasses: false
    lineNos: false
    codeFences: true
    guessSyntax: true
