name: Create new micro-blog post and populate Hugo frontmatter

on:
  issues:
    types:
      - labeled

jobs:
  create-post:
    # Restrict to my GitHub username to prevent the public from creating new blog posts
    if: github.actor == 'stochastical' && github.event.label.name == 'new-blog-post'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Parse Issue
        id: issue-parser
        uses: issue-ops/parser@v4.0.0
        with:
          body: ${{ github.event.issue.body }}
          issue-form-template: 'new-blog-post.yml'
      
      - name: Output parsed issue JSON
        id: output-issue
        run: |
          echo "\nRaw json output:\n"
          printf "%s" "${{ steps.issue-parser.outputs.json }}"
          
          echo "\nParsed JSON output with jq:\n"
          printf '%s' "${{ steps.issue-parser.outputs.json }}" | jq '.'

          echo "\nParsed JSON components with jq:\n"
          TITLE=$(printf '%s' "${{ steps.issue-parser.outputs.json }}" | jq '.title')
          DATE=$(printf '%s' "${{ steps.issue-parser.outputs.json }}" | jq '.date')
          DESCRIPTION=$(printf '%s' "${{ steps.issue-parser.outputs.json }}" | jq '.description')
          LINK=$(printf '%s' "${{ steps.issue-parser.outputs.json }}" | jq '.link')
          CONTENT=$(printf '%s' "${{ steps.issue-parser.outputs.json }}" | jq '.content')

          echo "\nParsed JSON output with jq:\n"
          FILENAME=$(echo "$DATE-$TITLE.md" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -d '[:punct:]')

          echo "{environment_variable_name}={value}" >> "$GITHUB_ENV"


      - name: Set up Hugo Blog post YAML frontmatter
        id: post-data
        env:
          ISSUE_BODY: "${{ github.event.issue.body }}"
        run: |
          # Generate post filename
          FILENAME=$(echo "$DATE-$TITLE.md" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -d '[:punct:]')
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV

      - name: Create blog post file
        run: |
          cat <<EOF > content/micro-blog/$FILENAME
          ---
          title: "$TITLE"
          date: $DATE
          description: "$DESCRIPTION"
          link: "$LINK"
          draft: false
          ---

          $CONTENT
          EOF

          cat content/micro-blog/$FILENAME

      # - name: Switch to preview branch
      #   run: |
      #     git checkout -B preview

      # - name: Commit and push changes
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git add content/blog/$FILENAME
      #     git commit -m "Add new blog post (via Actions): $TITLE"
      #     git push origin preview
